version: '2'
services:
  api:
    image: sncf/quitus
    build:
      context: .
      dockerfile: ./install/Dockerfile
    restart: always
    volumes:
      - ./app:/app
    ports:
      - 8080:8000
    depends_on:
      - db
      - redis
    env_file:
      - ./install/.postgres.env
      - ./install/.redis.env
      - ./install/.api.env

  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - ./install/.redis.env
    links:
      - db

  db:
    image: postgres:10-alpine
    restart: always
    env_file:
      - ./install/.postgres.env

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    links:
      - db 
    environment:
      - DATABASE_URL=postgres://docker:docker@db:5432/quitus?sslmode=disable
    depends_on:
      - db
    




