version: '2'
services:
  api:
    image: 5legs/api-cisco
    build:
      context: .
      dockerfile: ./install/Dockerfile
    restart: always
    volumes:
      - ./app:/app
    ports:
      - 8080:8000
    # depends_on:
    #   - db
    #   - redis
    env_file:
      # - ./install/.postgres.env
      # - ./install/.redis.env
      - ./install/.api.env

  # redis:
  #   image: redis:4
  #   command: ["redis-server", "--port", "6379"]
  #   restart: always
  #   env_file:
  #     - ./install/.redis.env
  #   ports:
  #     - 6379:6379

  # db:
  #   image: postgres
  #   restart: always
  #   env_file:
  #     - ./install/.postgres.env
    # ports:
    #   - 5432:5432




